/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Rudy Rachman
 */
public class Burgera extends javax.swing.JFrame {

    /**
     * Creates new form Burgera
     */
    public Burgera(){
        initComponents();
        placement();
        setKasir();
        pesanan.setText(setNomor());
    }
    public void placement(){
        setLocationRelativeTo(null);
        setTitle("Burgera Kasir Cepat");
        setResizable(false);
        pesanan.setEditable(false);
        DefaultTableCellRenderer dtr = new DefaultTableCellRenderer();
        dtr.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        menu.getColumnModel().getColumn(0).setCellRenderer(dtr);
        menu.getColumnModel().getColumn(1).setCellRenderer(dtr);
        burgera.getColumnModel().getColumn(0).setCellRenderer(dtr);
        burgera.getColumnModel().getColumn(1).setCellRenderer(dtr);
        priceAddOn.setVisible(false);
    }
    public void setKasir(){
        kasir.setText("KASIR: "+setgetKasir.user+" ("+setgetKasir.namaPanggilan+")");
        tanggal.setText(setgetKasir.getNowDate());
    }
    public String setNomor(){
        return con.nomorPesanan(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        kasir = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        makan = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        id = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        nama = new javax.swing.JEditorPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        satuan = new javax.swing.JEditorPane();
        priceAddOn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        addon = new javax.swing.JComboBox<>();
        PriceAdd = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hargaAdd = new javax.swing.JLabel();
        input = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        burgera = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        pesanan = new javax.swing.JEditorPane();
        total = new javax.swing.JLabel();
        bayar = new javax.swing.JButton();
        perbarui = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bersih = new javax.swing.JButton();
        batal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HEADER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 840, -1));

        tanggal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tanggal.setText("Tanggal");
        tanggal.setToolTipText("");
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 74, 340, -1));

        kasir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        kasir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kasir.setText("KASIR: ID (PANGGILAN)");
        kasir.setToolTipText("");
        getContentPane().add(kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 74, -1, -1));

        jenis.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JENIS", "PAKET", "BURGER", "MINUM" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 145, 108, -1));

        makan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        makan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAKAN DI?", "DINE-IN", "TAKE-OUT", "DELIVERY" }));
        makan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makanActionPerformed(evt);
            }
        });
        getContentPane().add(makan, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 110, -1, -1));

        id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        id.setForeground(new java.awt.Color(180, 180, 180));
        id.setText("ID");
        id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idFocusLost(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(id);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 186, 260, 40));

        nama.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nama.setForeground(new java.awt.Color(180, 180, 180));
        nama.setText("NAMA");
        nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namaFocusLost(evt);
            }
        });
        nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namaKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(nama);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 260, 80));

        satuan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        satuan.setForeground(new java.awt.Color(180, 180, 180));
        satuan.setText("SATUAN");
        satuan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                satuanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                satuanFocusLost(evt);
            }
        });
        satuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                satuanKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                satuanKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(satuan);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 190, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("HARGA:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Rp.");

        harga.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        harga.setText("xxxx");

        addon.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADD-ON" }));
        addon.setToolTipText("");
        addon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("HARGA:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Rp.");

        hargaAdd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        hargaAdd.setText("xxxx");

        javax.swing.GroupLayout PriceAddLayout = new javax.swing.GroupLayout(PriceAdd);
        PriceAdd.setLayout(PriceAddLayout);
        PriceAddLayout.setHorizontalGroup(
            PriceAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PriceAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(8, 8, 8)
                .addComponent(jLabel12)
                .addGap(0, 0, 0)
                .addComponent(hargaAdd)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        PriceAddLayout.setVerticalGroup(
            PriceAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PriceAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PriceAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hargaAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout priceAddOnLayout = new javax.swing.GroupLayout(priceAddOn);
        priceAddOn.setLayout(priceAddOnLayout);
        priceAddOnLayout.setHorizontalGroup(
            priceAddOnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priceAddOnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(priceAddOnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(priceAddOnLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8)
                        .addGap(0, 0, 0)
                        .addComponent(harga)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PriceAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        priceAddOnLayout.setVerticalGroup(
            priceAddOnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priceAddOnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(priceAddOnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(addon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PriceAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        getContentPane().add(priceAddOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 240, 110));

        input.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        input.setText("INPUT");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        getContentPane().add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 245, -1));

        menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAMA", "HARGA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        menu.setRowHeight(30);
        menu.setShowGrid(true);
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(menu);
        if (menu.getColumnModel().getColumnCount() > 0) {
            menu.getColumnModel().getColumn(0).setMinWidth(60);
            menu.getColumnModel().getColumn(0).setPreferredWidth(60);
            menu.getColumnModel().getColumn(0).setMaxWidth(60);
            menu.getColumnModel().getColumn(2).setMinWidth(90);
            menu.getColumnModel().getColumn(2).setPreferredWidth(90);
            menu.getColumnModel().getColumn(2).setMaxWidth(90);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, 130));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("PESANAN: ");

        burgera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAMA", "ADD-ONS", "JUMLAH", "HARGA", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        burgera.setRowHeight(30);
        burgera.setShowGrid(true);
        burgera.getTableHeader().setReorderingAllowed(false);
        burgera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                burgeraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(burgera);
        if (burgera.getColumnModel().getColumnCount() > 0) {
            burgera.getColumnModel().getColumn(1).setMinWidth(150);
            burgera.getColumnModel().getColumn(1).setPreferredWidth(150);
            burgera.getColumnModel().getColumn(1).setMaxWidth(150);
            burgera.getColumnModel().getColumn(2).setMinWidth(80);
            burgera.getColumnModel().getColumn(2).setPreferredWidth(80);
            burgera.getColumnModel().getColumn(2).setMaxWidth(80);
            burgera.getColumnModel().getColumn(3).setMinWidth(80);
            burgera.getColumnModel().getColumn(3).setPreferredWidth(80);
            burgera.getColumnModel().getColumn(3).setMaxWidth(80);
            burgera.getColumnModel().getColumn(4).setMinWidth(90);
            burgera.getColumnModel().getColumn(4).setPreferredWidth(90);
            burgera.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        pesanan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(pesanan);

        total.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        total.setText("TOTAL");

        bayar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bayar.setText("BAYAR");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        perbarui.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        perbarui.setText("PERBARUI");
        perbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perbaruiActionPerformed(evt);
            }
        });

        hapus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perbarui)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hapus)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, 0)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perbarui)
                    .addComponent(hapus)
                    .addComponent(total))
                .addGap(19, 19, 19)
                .addComponent(bayar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 110, -1, 590));

        cari.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cari.setText("CARI");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 107, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("PCS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        bersih.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bersih.setText("BERSIH");
        bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihActionPerformed(evt);
            }
        });
        getContentPane().add(bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 107, -1));

        batal.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        batal.setText("BATAL");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Fungsi fungsi = new Fungsi();
    private void idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusGained
        fungsi.focus(id, "ID", "",1);
    }//GEN-LAST:event_idFocusGained

    private void idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusLost
        fungsi.focus(id,"","ID",0);
    }//GEN-LAST:event_idFocusLost

    private void namaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaFocusGained
        fungsi.focus(nama, "NAMA", "",1);
    }//GEN-LAST:event_namaFocusGained

    private void namaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaFocusLost
        fungsi.focus(nama, "", "NAMA",0);
    }//GEN-LAST:event_namaFocusLost

    private void satuanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_satuanFocusGained
        fungsi.focus(satuan, "SATUAN", "",1);
    }//GEN-LAST:event_satuanFocusGained

    private void satuanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_satuanFocusLost
        fungsi.focus(satuan, "", "SATUAN",0);
    }//GEN-LAST:event_satuanFocusLost

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(!id.getText().equals("")) cari(0);
            evt.consume();
        }
        else if(evt.getKeyCode()==KeyEvent.VK_TAB){
            nama.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_idKeyPressed

    private void namaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(!id.getText().equals("")) cari(1);
            evt.consume();
        }
        else if(evt.getKeyCode()==KeyEvent.VK_TAB){
            cari.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_namaKeyPressed
    boolean click=false;
    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        int baris = menu.getSelectedRow();
        TableModel model = menu.getModel();
        unLockIdNama(false);
        id.setText(model.getValueAt(baris, 0).toString());
        nama.setText(model.getValueAt(baris, 1).toString());
        harga.setText(String.valueOf(listHarga[baris]));
    }//GEN-LAST:event_menuMouseClicked

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        if(click&&!pesananClick){
            if(satuan.getText().equals("SATUAN")){
                JOptionPane.showMessageDialog(this,"Masukkan Satuan Terlebih dahulu","Peringatan!",JOptionPane.WARNING_MESSAGE);
                satuan.requestFocus();
            }
            else if(makan.getSelectedItem().equals("MAKAN DI?")){
                JOptionPane.showMessageDialog(this,"Tentukan makan di mana","Peringatan!",JOptionPane.WARNING_MESSAGE);
                makan.requestFocus();
            }
            else{
                int satuan = Integer.valueOf(this.satuan.getText()), harga = Integer.valueOf(this.harga.getText()), addHarga=0;
                String id = this.id.getText(), addNama="", idKasir = setgetKasir.user,tanggal=setgetKasir.getDateForDB();
                if(addon.getSelectedIndex()==0){
                    addNama="";
                    addHarga=0;
                }
                else{
                    addHarga=this.addOn.get(this.addon.getSelectedIndex()-1).getHarga();
                    addNama=addon.getSelectedItem().toString();
                }
                banyakPesanan++;
                hargaAddOndpsn.add(banyakPesanan,addHarga);
                con.inputPesanan(pesanan.getText(), idKasir, id, addNama, satuan, harga+addHarga, makan.getSelectedItem().toString(), tanggal);
                tabelPesanan(con.showPesanan(pesanan.getText()));
                clear();
            }
        }
        else if(pesananClick){
            JOptionPane.showMessageDialog(this, "Tidak boleh tekan Input","Peringatan!",JOptionPane.WARNING_MESSAGE);
            perbarui.requestFocus();
        }
        else{
            JOptionPane.showMessageDialog(this,"Masukkan ID atau Nama terlebih dahulu","Peringatan!",JOptionPane.WARNING_MESSAGE);
            if(id.getText().equals("ID"))id.requestFocus();
            else if(nama.getText().equals("NAMA")) nama.requestFocus();
            else cari.requestFocus();
        }
    }//GEN-LAST:event_inputActionPerformed
    int banyakPesanan=-1;
    ArrayList<Integer> hargaAddOndpsn = new ArrayList<>();
    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        if(!id.getText().equals("ID"))cari(0);
        else if(!nama.getText().equals("NAMA"))cari(1);
        else JOptionPane.showMessageDialog(this,"Isi Id atau Nama terlebih dahulu lalu tekan enter","Peringatan!",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_cariActionPerformed

    private void satuanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_satuanKeyPressed
        fungsi.pindah(satuan, input, evt);
    }//GEN-LAST:event_satuanKeyPressed

    private void bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihActionPerformed
        clear();
    }//GEN-LAST:event_bersihActionPerformed

    private void satuanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_satuanKeyTyped
        fungsi.numberOnly(satuan, evt, 5);
    }//GEN-LAST:event_satuanKeyTyped

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        if(jenis.getSelectedIndex()!=0){
            ArrayList<MenuPesan> al = con.jenisChange(jenis.getSelectedItem().toString());
            setListHarga(al);
            menuTable(al);
        }  
    }//GEN-LAST:event_jenisActionPerformed
    int selectedIndeks, baris;
    private void burgeraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_burgeraMouseClicked
        unLockIdNama(false);
        pesananClick=true;
        int baris = burgera.getSelectedRow();
        this.baris=baris;
        TableModel model = burgera.getModel();
        selectedIndeks = indeks[baris];
        id.setText(untukPesanan.get(baris).getId());
        nama.setText(model.getValueAt(baris,0).toString());
        if(model.getValueAt(baris,1).equals("")) addon.setSelectedIndex(0);
        else{
            int i=0;
            for(MenuPesan mp:addOn){
                if(model.getValueAt(baris,1).toString().equals(mp.getNama()))
                    break;
                i++;
            }
            addon.setSelectedIndex(i+1);
        }
        satuan.setText(model.getValueAt(baris,2).toString());
        harga.setText(model.getValueAt(baris,3).toString());
        satuan.requestFocus();
    }//GEN-LAST:event_burgeraMouseClicked

    private void perbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perbaruiActionPerformed
        if(pesananClick){
            if(satuan.getText().equals("SATUAN")){
                JOptionPane.showMessageDialog(this,"Masukkan Satuan Terlebih dahulu","Peringatan!",JOptionPane.WARNING_MESSAGE);
                satuan.requestFocus();
            }
            else{
                String addNama="";
                int addHarga=0;
                if(addon.getSelectedIndex()!=0){
                    addNama = addOn.get(addon.getSelectedIndex()-1).getNama();
                    addHarga = addOn.get(addon.getSelectedIndex()-1).getHarga();
                }
                hargaAddOndpsn.set(baris, addHarga);
                con.updatePesanan(Integer.valueOf(satuan.getText()), selectedIndeks, addNama, addHarga + Integer.valueOf(harga.getText()));
                JOptionPane.showMessageDialog(this, "Update Berhasil!","Informasi!",JOptionPane.INFORMATION_MESSAGE);
                clear();
                pesananClick=false;
                tabelPesanan(con.showPesanan(pesanan.getText()));
            }
        }
        else{
            burgera.requestFocus();
            JOptionPane.showMessageDialog(this,"Klik yang ingin diubah","Informasi!",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_perbaruiActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        if(pesananClick){
            hargaAddOndpsn.remove(baris);
            banyakPesanan--;
            con.deletePesanan(selectedIndeks);
            JOptionPane.showMessageDialog(this, "Delete Berhasil!","Informasi!",JOptionPane.INFORMATION_MESSAGE);
            clear();
            pesananClick=false;
            tabelPesanan(con.showPesanan(pesanan.getText()));
        }
        else{
            burgera.requestFocus();
            JOptionPane.showMessageDialog(this,"Klik yang ingin dihapus","Informasi!",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void addonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addonActionPerformed
        if(addon.getSelectedIndex()>0){
            PriceAdd.setVisible(true);
            hargaAdd.setText(String.valueOf(addOn.get(addon.getSelectedIndex()-1).getHarga()));
        }
    }//GEN-LAST:event_addonActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        int totalAll=0;
        Print print = new Print();
        String header = "	                 KASIR CEPAT\n"
                + "	                   BURGERA\n"
                + "KASIR: "+setgetKasir.namaPanggilan+"\n"
                + String.format("%48s\n", setgetKasir.getNowDateNoto())
                + String.format("%27s\n", "("+makan.getSelectedItem().toString()+")")
                + "====================================================\n"
                + "	                   PESANAN\n"
                + "====================================================\n";
        int index=0;
        String isi="";
        for(TabelPesanan tp : untukPesanan){
            int total=tp.getSatuan()*tp.getHarga();
            String makanan=String.format("%s \n", tp.getNama());
            String add=String.format("%16s  %5s%d\n","Add-On: "+tp.getAddon(),"+Rp.",hargaAddOndpsn.get(index));
            index++;
            String angka=String.format("%9d x Rp.%d %21s%d\n",tp.getSatuan(),tp.getHarga(),"Rp.",total);
            isi+=makanan+add+angka;
            totalAll+=total;
        }
        String footer="Total: "+String.format("%35s%d", "Rp.",totalAll)+"\n"
                + "====================================================\n"
                + "        TERIMA KASIH ATAS KUNJUNGANNYA\n"
                + "               DATANG LAGI YA :)";
        print.setPrint(header, isi, footer);
        print.setVisible(true);
        print.setJFrame(this);
    }//GEN-LAST:event_bayarActionPerformed

    private void makanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makanActionPerformed
        if(makan.getSelectedIndex()!=0)
            makan.setEnabled(false);
    }//GEN-LAST:event_makanActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        fungsi.batal(0, pesanan.getText(),this);
    }//GEN-LAST:event_batalActionPerformed
    boolean pesananClick = false;
    public void clear(){
        unLockIdNama(true);
        pesananClick=false;
        id.setText("ID");
        nama.setText("NAMA");
        satuan.setText("SATUAN");
    }
    
    ConnectDB con = new ConnectDB();
    int[] listHarga;
    public void setListHarga(ArrayList<MenuPesan> al){
        listHarga = new int[al.size()];
        int index=0;
        for(MenuPesan mp:al){
            listHarga[index]=mp.getHarga();
            index++;
        }
    }
    public void cari(int opsi){
        ArrayList<MenuPesan> al = new ArrayList<>();
        if(opsi==0) al=con.cariMenu(id.getText(), opsi);
        else al=con.cariMenu(nama.getText(), opsi);
        if(al.isEmpty()){
            JOptionPane.showMessageDialog(this,"Tidak ditemukan","Peringatan!",JOptionPane.WARNING_MESSAGE);
            if(opsi==0){
                if(nama.getText().equals("NAMA")) nama.requestFocus();
            }
            else{
                if(id.getText().equals("ID")) id.requestFocus();
            }
        }
        else{
            if(opsi==0){
                id.setText(al.get(0).getId());
                nama.setText(al.get(0).getNama());
                unLockIdNama(false);
                satuan.requestFocus();
                harga.setText(String.valueOf(al.get(0).getHarga()));
            }
            setListHarga(al);
            menuTable(al);
        }
    }
    
    ArrayList<MenuPesan> addOn;
    public void setAddOn(){
        PriceAdd.setVisible(false);
        this.addOn = con.addOn();
        addon.removeAllItems();
        addon.addItem("ADD-ON");
        for(MenuPesan mp:addOn)
            addon.addItem(mp.getNama());
    }
    
    public void unLockIdNama(boolean status){
        jenis.setEnabled(status);
        id.setEditable(status);
        nama.setEditable(status);
        click = !status;
        priceAddOn.setVisible(!status);
        setAddOn();
    }
    public void menuTable(ArrayList<MenuPesan> al){
        DefaultTableModel model = (DefaultTableModel) menu.getModel();
        Object baris[] = new Object[3];
        model.setRowCount(0);
        for(MenuPesan mp:al){
            baris[0] = mp.getId();
            baris[1] = mp.getNama();
            baris[2] = mp.getHarga();
            model.addRow(baris);
        }
    }
    
    int[] indeks;
    ArrayList<TabelPesanan> untukPesanan;
    public void tabelPesanan(ArrayList<TabelPesanan> al){
        untukPesanan = al;
        indeks = new int[al.size()];
        DefaultTableModel model = (DefaultTableModel) burgera.getModel();
        Object baris[] = new Object[5];
        model.setRowCount(0);
        int total=0;
        int i = 0;
        for(TabelPesanan tp:al){
            indeks[i] = tp.getIndeks();
            baris[0] = tp.getNama();
            baris[1] = tp.getAddon();
            baris[2] = tp.getSatuan();
            baris[3] = tp.getHarga();
            baris[4] = tp.getHarga()*tp.getSatuan();
            total += (int) baris[4]; //object bisa cast(ubah dengan kurung), tanpa parse atau valueOf
            model.addRow(baris);
            i++;
        }
        this.total.setText("Rp."+String.valueOf(total));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Burgera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Burgera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Burgera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Burgera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Burgera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PriceAdd;
    private javax.swing.JComboBox<String> addon;
    private javax.swing.JButton batal;
    private javax.swing.JButton bayar;
    private javax.swing.JButton bersih;
    private javax.swing.JTable burgera;
    private javax.swing.JButton cari;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel hargaAdd;
    private javax.swing.JEditorPane id;
    private javax.swing.JButton input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel kasir;
    private javax.swing.JComboBox<String> makan;
    private javax.swing.JTable menu;
    private javax.swing.JEditorPane nama;
    private javax.swing.JButton perbarui;
    private javax.swing.JEditorPane pesanan;
    private javax.swing.JPanel priceAddOn;
    private javax.swing.JEditorPane satuan;
    private javax.swing.JLabel tanggal;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
