/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Rudy Rachman
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Buat Akun");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Isi = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        username = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        nama = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        panggilan = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        telepon = new javax.swing.JEditorPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        kode = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        login = new javax.swing.JLabel();
        create = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(233, 231, 97));
        Header.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(233, 231, 97));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buat Akun");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Isi.setBackground(new java.awt.Color(207, 189, 119));

        jScrollPane1.setForeground(new java.awt.Color(180, 180, 180));

        username.setText("Username");
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(username);

        jScrollPane3.setForeground(new java.awt.Color(180, 180, 180));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        nama.setText("Nama Lengkap");
        nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namaFocusLost(evt);
            }
        });
        nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namaKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(nama);

        jScrollPane4.setForeground(new java.awt.Color(180, 180, 180));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panggilan.setText("Nama Panggilan");
        panggilan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panggilanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                panggilanFocusLost(evt);
            }
        });
        panggilan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panggilanKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                panggilanKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(panggilan);

        jScrollPane5.setForeground(new java.awt.Color(180, 180, 180));
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        telepon.setText("Nomor Telepon");
        telepon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teleponFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teleponFocusLost(evt);
            }
        });
        telepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teleponKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teleponKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(telepon);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        kode.setText("62");
        jScrollPane6.setViewportView(kode);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("+");

        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setText("Password");
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });

        jScrollPane2.setForeground(new java.awt.Color(180, 180, 180));

        alamat.setColumns(20);
        alamat.setLineWrap(true);
        alamat.setRows(5);
        alamat.setText("Alamat");
        alamat.setMargin(new java.awt.Insets(1, 2, 1, 2));
        alamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alamatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alamatFocusLost(evt);
            }
        });
        alamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                alamatKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(alamat);

        login.setForeground(new java.awt.Color(83, 122, 203));
        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });

        create.setBackground(new java.awt.Color(0, 0, 0));
        create.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setText("Buat Akun");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IsiLayout = new javax.swing.GroupLayout(Isi);
        Isi.setLayout(IsiLayout);
        IsiLayout.setHorizontalGroup(
            IsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IsiLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(IsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(IsiLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(3, 3, 3)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(IsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login)
                    .addComponent(jScrollPane2)
                    .addComponent(create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );
        IsiLayout.setVerticalGroup(
            IsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IsiLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(IsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(IsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(IsiLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login)
                .addGap(16, 16, 16)
                .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Isi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Isi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        changeCursor(1);
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        changeCursor(0);
    }//GEN-LAST:event_loginMouseExited

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        Login loginMenu = new Login();
        loginMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginMouseClicked

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        if(username.getText().equals("Username")) username.setText("");
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        if(username.getText().equals("")) username.setText("Username");
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        password.setText("");
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if(Arrays.toString(password.getPassword()).equals("[]")) password.setText("Password");
    }//GEN-LAST:event_passwordFocusLost

    private void namaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaFocusGained
        if(nama.getText().equals("Nama Lengkap")) nama.setText("");
    }//GEN-LAST:event_namaFocusGained

    private void namaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaFocusLost
        if(nama.getText().equals("")) nama.setText("Nama Lengkap");
    }//GEN-LAST:event_namaFocusLost

    private void panggilanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panggilanFocusGained
        if(panggilan.getText().equals("Nama Panggilan")) panggilan.setText("");
    }//GEN-LAST:event_panggilanFocusGained

    private void panggilanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panggilanFocusLost
        if(panggilan.getText().equals("")) panggilan.setText("Nama Panggilan");
    }//GEN-LAST:event_panggilanFocusLost

    private void teleponFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teleponFocusGained
        if(telepon.getText().equals("Nomor Telepon")) telepon.setText("");
    }//GEN-LAST:event_teleponFocusGained

    private void teleponFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teleponFocusLost
        if(telepon.getText().equals("")) telepon.setText("Nomor Telepon");
    }//GEN-LAST:event_teleponFocusLost

    private void alamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alamatFocusGained
        if(alamat.getText().equals("Alamat")) alamat.setText("");
    }//GEN-LAST:event_alamatFocusGained

    private void alamatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alamatFocusLost
        if(alamat.getText().equals("")) alamat.setText("Alamat");
    }//GEN-LAST:event_alamatFocusLost

    private void namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaKeyTyped
        disableAlpha(evt,nama,50);
    }//GEN-LAST:event_namaKeyTyped

    private void panggilanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panggilanKeyTyped
        disableAlpha(evt,panggilan,25);
    }//GEN-LAST:event_panggilanKeyTyped

    private void teleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teleponKeyTyped
        disableNum(evt,telepon,14);
    }//GEN-LAST:event_teleponKeyTyped

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_TAB){
            if(username.getText().equals(""))
                username.requestFocus();
            else password.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_usernameKeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_TAB){
            if(Arrays.toString(password.getPassword()).equals("[]"))
                password.requestFocus();
            else nama.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_passwordKeyPressed

    private void namaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaKeyPressed
        pressEnterorTab(evt, nama, panggilan);
    }//GEN-LAST:event_namaKeyPressed

    private void panggilanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panggilanKeyPressed
        pressEnterorTab(evt, panggilan, telepon);
    }//GEN-LAST:event_panggilanKeyPressed

    private void teleponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teleponKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_TAB){//evt.getKeyCode() Mesti paling atas dari if, kalau di bawa nda tebaca
            if(telepon.getText().length()>=9){
                alamat.requestFocus();
                evt.consume();
            }
            else{
                telepon.requestFocus();
                evt.consume();
            }
        }
    }//GEN-LAST:event_teleponKeyPressed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        String username="", password="", namaLengkap="", namaPanggilan="", noHp="", alamat="";
        boolean empty=false;
        
        if(!this.username.getText().equals("Username")) username = this.username.getText().toLowerCase().trim();
        else empty=true;
        if(!this.nama.getText().equals("Nama Lengkap")) namaLengkap = this.nama.getText().toUpperCase().trim();
        else empty=true;
        if(!this.panggilan.getText().equals("Nama Panggilan")) namaPanggilan = this.panggilan.getText().trim().toUpperCase();
        else empty=true;
        if(!this.telepon.getText().equals("Nomor Telepon")){
            if(this.telepon.getText().matches("^0*"))
                noHp = this.telepon.getText().replaceAll("^0*", "");
        }
        else empty=true;
        if(Arrays.toString(this.password.getPassword()).equals("[]")) empty = true;
        else{
            for(char a:this.password.getPassword())
                password+=a;
        }
        if(this.alamat.getText().equals("")) alamat="...";
        else alamat = this.alamat.getText();
        
        if(!empty){
            ConnectDB con = new ConnectDB();
            boolean bisa = con.createAccount(username, password, namaLengkap, namaPanggilan, noHp, alamat);
            if(bisa){
                Login login = new Login();
                login.setVisible(true);
                this.dispose();
            }
            else{
                this.username.setText("Username");
                this.username.requestFocus();
            }
        }
        else JOptionPane.showMessageDialog(this, "Username/Password/Nama Lengkap/Nama Panggilan/Nomor Telepon\nTidak boleh kosong",
                "Error!", JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_createActionPerformed

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        char a = evt.getKeyChar();
        if(Character.isSpaceChar(a)) evt.consume();
    }//GEN-LAST:event_usernameKeyTyped

    private void alamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alamatKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_TAB) create.requestFocus();
    }//GEN-LAST:event_alamatKeyPressed
    public void changeCursor(int status){
        Cursor cursor;
        if(status==1) cursor = new Cursor(Cursor.HAND_CURSOR);
        else cursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(cursor);
    }
    public void disableAlpha(java.awt.event.KeyEvent evt, javax.swing.JEditorPane kotak, int batas){
        char abj = evt.getKeyChar();
        if(!(Character.isAlphabetic(abj)||Character.isSpaceChar(abj))) evt.consume();
        if(!(kotak.getText().length()<batas-1)) evt.consume();
    }
    public void disableNum(java.awt.event.KeyEvent evt, javax.swing.JEditorPane kotak, int batas){
        char abj = evt.getKeyChar();
        if(!(Character.isDigit(abj)))evt.consume();
        if(!(kotak.getText().length()<batas-1)) evt.consume();
    }
    public void pressEnterorTab(java.awt.event.KeyEvent evt, javax.swing.JEditorPane asal, javax.swing.JEditorPane tujuan){
        if(evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_TAB){
            if(asal.getText().equals(""))
                asal.requestFocus();
            else tujuan.requestFocus();
            evt.consume();
        }        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Isi;
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JEditorPane kode;
    private javax.swing.JLabel login;
    private javax.swing.JEditorPane nama;
    private javax.swing.JEditorPane panggilan;
    private javax.swing.JPasswordField password;
    private javax.swing.JEditorPane telepon;
    private javax.swing.JEditorPane username;
    // End of variables declaration//GEN-END:variables
}
