/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author Rudy Rachman
 */

public class Menu extends javax.swing.JFrame {
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Main Menu");
        setLocationRelativeTo(null);
        setResizable(false);
        setKasir(setgetKasir.namaPanggilan,setgetKasir.user);
    }
    public final void setKasir(String nama, String user){
        kasir.setText("KASIR: "+user);
        halo.setText("Halo "+nama);
        tanggal.setText(setgetKasir.getNowDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        burgera = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        kasir = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        halo = new javax.swing.JLabel();
        foodMenu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        bulanan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        burgera.setBackground(new java.awt.Color(0, 0, 0));
        burgera.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        burgera.setForeground(new java.awt.Color(255, 255, 255));
        burgera.setText("BURGERA");
        burgera.setMaximumSize(new java.awt.Dimension(95, 40));
        burgera.setMinimumSize(new java.awt.Dimension(95, 40));
        burgera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgeraActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PENGELUARAN");
        jButton2.setMaximumSize(new java.awt.Dimension(95, 40));
        jButton2.setMinimumSize(new java.awt.Dimension(95, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        kasir.setForeground(new java.awt.Color(0, 0, 0));
        kasir.setText("KASIR: ");

        tanggal.setForeground(new java.awt.Color(0, 0, 0));
        tanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tanggal.setText("TANGGAL");

        halo.setForeground(new java.awt.Color(0, 0, 0));
        halo.setText("NAMA: ");

        foodMenu.setBackground(new java.awt.Color(0, 0, 0));
        foodMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        foodMenu.setForeground(new java.awt.Color(255, 255, 255));
        foodMenu.setText("Set Food Menu");
        foodMenu.setMaximumSize(new java.awt.Dimension(95, 40));
        foodMenu.setMinimumSize(new java.awt.Dimension(95, 40));
        foodMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodMenuActionPerformed(evt);
            }
        });

        jMenu1.setText("Cek");

        bulanan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        bulanan.setText("PEMASUKAN BULANAN");
        bulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulananActionPerformed(evt);
            }
        });
        jMenu1.add(bulanan);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(burgera, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kasir)
                    .addComponent(halo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kasir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(halo))
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(foodMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(burgera, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void foodMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodMenuActionPerformed
        FoodMenu fm = new FoodMenu();
        fm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_foodMenuActionPerformed

    private void burgeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgeraActionPerformed
        Burgera b = new Burgera();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_burgeraActionPerformed

    private void bulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulananActionPerformed
        Omset bulan = new Omset();
        bulan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bulananActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Belanja belanja = new Belanja();
        belanja.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bulanan;
    private javax.swing.JButton burgera;
    private javax.swing.JButton foodMenu;
    private javax.swing.JLabel halo;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel kasir;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables
}
