/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rudy Rachman
 */
public class Omset extends javax.swing.JFrame {

    /**
     * Creates new form Omset
     */
    public Omset() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("HITUNG OMSET");
        setResizable(false);
        omset.setVisible(false);
        omset1.setVisible(false);
        dari.setFormats("yyyy-MM-dd");
        sampai.setFormats("yyyy-MM-dd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dari = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        sampai = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        cari = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pembelian = new javax.swing.JTable();
        totalBeli = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        penjualan = new javax.swing.JTable();
        total = new javax.swing.JLabel();
        omset = new javax.swing.JLabel();
        omset1 = new javax.swing.JLabel();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REKAP PENGHASILAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 0, 760, -1));
        getContentPane().add(dari, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 72, 153, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dari Tanggal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 50, 114, -1));
        getContentPane().add(sampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 72, 153, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sampai Tanggal");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 50, 114, -1));

        cari.setText("CARI");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 108, 900, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 146, 13, 361));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PEMBELIAN");

        pembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TANGGAL", "NOMOR PESANAN", "TOTAL (Rp.)"
            }
        ));
        pembelian.setShowGrid(true);
        pembelian.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(pembelian);

        totalBeli.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        totalBeli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalBeli.setText("TOTAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(totalBeli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalBeli))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 146, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PENJUALAN");

        penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TANGGAL", "NOMOR PESANAN", "TOTAL (Rp.)"
            }
        ));
        penjualan.setShowGrid(true);
        penjualan.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(penjualan);

        total.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        total.setText("TOTAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 146, -1, 361));

        omset.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        omset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        omset.setText("OMSET");
        getContentPane().add(omset, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 519, 479, -1));

        omset1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        omset1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        omset1.setText("Rp.");
        getContentPane().add(omset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 519, 433, -1));

        print.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        print.setText("CETAK STRUK");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 183, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed
    ConnectDB con = new ConnectDB();
    ArrayList<NomorDanTanggal> list=new ArrayList();
    ArrayList<NomorDanTanggal> listBeli = new ArrayList();
    ArrayList<Integer> al = new ArrayList();
    ArrayList<Integer> alBeli = new ArrayList();
    public String parseDateToString(Date tanggal){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String kata = sdf.format(tanggal);
        return kata;
    }
    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        if(dari.getDate()==null||sampai.getDate()==null) JOptionPane.showMessageDialog(this, "Tidak boleh ada yang kosong","PERINGATAN!",JOptionPane.WARNING_MESSAGE);
        else{
            ArrayList<NomorDanTanggal> list = con.getNomorPesananFromTanggal(parseDateToString(dari.getDate()), parseDateToString(sampai.getDate()), 0);
            DefaultTableModel model = (DefaultTableModel) penjualan.getModel();
            model.setRowCount(0);
            if(list.isEmpty())JOptionPane.showMessageDialog(this, "Tidak ada yang ditampilkan di tabel PENJUALAN", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
            else{
                ArrayList<Integer> al = con.getTotal(list, 0);
                this.list=list;
                this.al=al;
                Object baris[] = new Object[3];
                int total=0;
                for(int i=0;i<al.size();i++){
                    baris[0]=list.get(i).getTanggal();
                    baris[1]=list.get(i).getNomorPesanan();
                    baris[2]=al.get(i);
                    total+=al.get(i);
                    model.addRow(baris);
                }
                this.total.setText(String.valueOf(total));
            }
            ArrayList<NomorDanTanggal> listBeli = con.getNomorPesananFromTanggal(parseDateToString(dari.getDate()), parseDateToString(sampai.getDate()), 1);
            DefaultTableModel modelBeli = (DefaultTableModel) pembelian.getModel();
            modelBeli.setRowCount(0);
            if(listBeli.isEmpty())JOptionPane.showMessageDialog(this, "Tidak ada yang ditampilkan di tabel PEMBELIAN", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
            else{
                ArrayList<Integer> alBeli = con.getTotal(listBeli, 1);
                this.listBeli=listBeli;
                this.alBeli=alBeli;
                Object baris[] = new Object[3];
                int total=0;
                for(int i=0;i<alBeli.size();i++){
                    baris[0]=listBeli.get(i).getTanggal();
                    baris[1]=listBeli.get(i).getNomorPesanan();
                    baris[2]=alBeli.get(i);
                    total+=alBeli.get(i);
                    modelBeli.addRow(baris);
                }
                this.totalBeli.setText(String.valueOf(total));
            }
            int totalBeli,totalJual;
            if(this.totalBeli.getText().equals("TOTAL")) totalBeli=0;
            else totalBeli=Integer.valueOf(this.totalBeli.getText());
            if(this.total.getText().equals("TOTAL")) totalJual=0; 
            else totalJual= Integer.valueOf(this.total.getText());
            int omset;
            if(totalJual==0) omset = totalBeli;
            else omset = totalJual-totalBeli;
            this.omset.setText(String.valueOf(omset));
            this.omset.setVisible(true);
            this.omset1.setVisible(true);
        }
    }//GEN-LAST:event_cariActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        if(list==null&&listBeli==null) JOptionPane.showMessageDialog(this, "Tidak bisa print karena kosong","PERINGATAN!",JOptionPane.WARNING_MESSAGE);
        else{
            if(list.isEmpty()&&listBeli.isEmpty()) JOptionPane.showMessageDialog(this, "Tidak bisa print karena kosong","PERINGATAN!",JOptionPane.WARNING_MESSAGE);
            else{
                String header = "	                  KASIR CEPAT\n"
                        + "	                    BURGERA\n"
                        + "KASIR: "+setgetKasir.namaPanggilan+"\n"
                        + String.format("%48s\n", setgetKasir.getNowDateNoto())
                        + String.format("%26s\n","OMSET")
                        + "====================================================\n"
                        + "	               PENGHITUNGAN OMSET\n"
                        + "====================================================\n";
                String isi="";
                int total=0,totalBeli=0;
                isi+="PENJUALAN:\n";
                if(list!=null){
                    if(!list.isEmpty()){
                        for(int i=0;i<list.size();i++){
                            String tanggal,nomor;
                            if(i!=0){
                                if(list.get(i).getTanggal().equals(list.get(i-1).getTanggal())) tanggal="";
                                else tanggal="  "+list.get(i).getTanggal()+":\n";
                            }else tanggal="  "+list.get(i).getTanggal()+":\n";
                            nomor=String.format("%16s  %16s%d\n",list.get(i).getNomorPesanan(),"Rp.",al.get(i));
                            total+=al.get(i);
                            isi+=tanggal+nomor;
                        }
                        isi+="Total PENJUALAN: "+String.format("%19s%d", "Rp.",total)+"\n";
                    }else isi+="           KOSONG\n";
                }else isi+="           KOSONG\n";
                isi+="PEMBELIAN:\n";
                if(listBeli!=null){
                    if(!listBeli.isEmpty()){
                        for(int i=0;i<listBeli.size();i++){
                            String tanggal,nomor;
                            if(i!=0){
                                if(listBeli.get(i).getTanggal().equals(listBeli.get(i-1).getTanggal())) tanggal="";
                                else tanggal="  "+listBeli.get(i).getTanggal()+":\n";
                            }else tanggal="  "+listBeli.get(i).getTanggal()+":\n";
                            nomor=String.format("%16s  %16s%d\n",listBeli.get(i).getNomorPesanan(),"Rp.",alBeli.get(i));
                            totalBeli+=alBeli.get(i);
                            isi+=tanggal+nomor;
                        }
                        isi+="Total PEMBELIAN: "+String.format("%19s%d", "Rp.",totalBeli)+"\n";
                    }
                    else isi+="           KOSONG\n";
                }else isi+="           KOSONG\n";
                isi+="====================================================";
                int omset;
                if(list.isEmpty()) omset=totalBeli;
                else omset=total-totalBeli;
                String footer="Total OMSET: "+String.format("%23s%d", "Rp.",omset)+"\n"
                        + "====================================================\n";
                Print print = new Print();
                print.setPrint(header,isi,footer);
                print.setVisible(true);
                print.setJFrame(this);
            }
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Omset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Omset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Omset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Omset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Omset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cari;
    private org.jdesktop.swingx.JXDatePicker dari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel omset;
    private javax.swing.JLabel omset1;
    private javax.swing.JTable pembelian;
    private javax.swing.JTable penjualan;
    private javax.swing.JButton print;
    private org.jdesktop.swingx.JXDatePicker sampai;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalBeli;
    // End of variables declaration//GEN-END:variables
}
