/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.awt.Graphics2D;
import javax.swing.JFrame;

/**
 *
 * @author Rudy Rachman
 */
public class Print extends javax.swing.JFrame {

    /**
     * Creates new form Print
     */
    public Print() {
        initComponents();
        setTitle("Print Layout");
        isiPrint.setEditable(false);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        isiPrint = new javax.swing.JTextArea();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        isiPrint.setColumns(20);
        isiPrint.setFont(new java.awt.Font("Monospaced", 0, 8)); // NOI18N
        isiPrint.setRows(5);
        isiPrint.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(isiPrint);

        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(print)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JFrame dibawah;
    public void setJFrame(JFrame dibawah){
        this.dibawah=dibawah;
    }
    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setPrintable(new PrintArea(), page(pj,isiPrint.getText().split("\n")));
        if(pj.printDialog()){
            try{
                pj.print();
                Menu menu = new Menu();
                menu.setVisible(true);
                this.dispose();
                dibawah.dispose();
            }catch(Exception e){e.printStackTrace();}
        }
    }//GEN-LAST:event_printActionPerformed
    public PageFormat page(PrinterJob pj, String isi[]){
        PageFormat pf = pj.defaultPage();
        Paper paper = pf.getPaper();
        int height =5, indeks=isi.length;
        while(indeks>=0){
            if(!(height>indeks)){
                height+=5;
                indeks-=6;
            }
            else break;
        }
        System.out.println(height);
        paper.setSize(convertCmToPPI(8), convertCmToPPI(height));
        paper.setImageableArea(5, 5, convertCmToPPI(8), convertCmToPPI(height)-convertCmToPPI(1));
        pf.setOrientation(PageFormat.PORTRAIT);
        pf.setPaper(paper);
        return pf;
    }
    public double convertCmToPPI(double angka){
        return angka*0.393600787*79d;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print().setVisible(true);
            }
        });
    }
    public void setPrint(String header, String isi, String footer){
        isiPrint.setText(header+"\n"+isi+"\n"+footer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea isiPrint;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
    public class PrintArea implements Printable{
        @Override
        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
            int printed = NO_SUCH_PAGE;
            if(pageIndex==0){
                Graphics2D g2d = (Graphics2D) graphics;
                g2d.translate((int)pageFormat.getImageableX(), (int)pageFormat.getImageableY());
                try{
                    int baris=20;
                    int enter=10;
                    String isi[] = isiPrint.getText().split("\n");
                    g2d.setFont(new Font("Monospaced",Font.PLAIN,8));
                    for(String a:isi){
                        g2d.drawString(a, 12, baris);
                        baris+=enter;
                    }
                }catch(Exception e){e.printStackTrace();}
                printed = PAGE_EXISTS;
            }
            return printed;
        }
        
    }
}
